Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -109,7 +109,7 @@ jobs:
           echo "-------- Validate efficientdet-${version} FP32 IR --------"
           ln -sf efficientdet-${version}-FP32/efficientdet-${version}.bin ./efficientdet-${version}.bin
           ln -sf efficientdet-${version}-FP32/efficientdet-${version}.xml ./efficientdet-${version}.xml
-          python3 scripts/validate.py --version ${version} --width ${size} --height ${size}
+          python3 scripts/validate.py --version ${version} --width ${size} --height ${size} | grep -iv cuda
 
           rm -f ./efficientdet-${version}.xml
           rm -f ./efficientdet-${version}.bin
@@ -117,7 +117,7 @@ jobs:
           echo "-------- Validate efficientdet-${version} FP16 IR --------"
           ln -sf efficientdet-${version}-FP16/efficientdet-${version}.bin ./efficientdet-${version}.bin
           ln -sf efficientdet-${version}-FP16/efficientdet-${version}.xml ./efficientdet-${version}.xml
-          python3 scripts/validate.py --version ${version} --width ${size} --height ${size} || true # don't fail on this one.
+          python3 scripts/validate.py --version ${version} --width ${size} --height ${size} | grep -iv cuda || true # don't fail on this one.
           
           rm -f ./efficientdet-${version}.xml
           rm -f ./efficientdet-${version}.bin
